#!/usr/bin/env bash
# This script uses fetches a necessay info about the domain name

info_analyser()
{
	cutted_section=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4 " " $5}')
	echo "$cutted_section" "$2" | awk '{print "The subdomain " $3 " is a " $1 " record and points to " $2}'
}

if [ "$#" == 2 ]
then
	info_analyser "$1" "$2"
else
	info_analyser "$1" "www"
	info_analyser "$1" "lb-01"
	info_analyser "$1" "web-01"
	info_analyser "$1" "web-02"
fi
