#!/usr/bin/env bash

# a script that transfers a file from client to server.
# usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

if [[ "${#@}" -lt 4 ]]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	path="$1"
	ip="$2"
	username="$3"
	path_to_ssh_key="$4"
	# shellcheck disable=2088
scp -i "$path_to_ssh_key" -o "StrinctHostKeyChecking no" "$username@$ip":'~/' "$path"
fi
