#!/usr/bin/env bash

# a script that transfers a file from client to server.
# usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"
if [[ "$#" -lt 3 ]]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [[ "$#" -lt 3 ]]; then
	scp -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP":~/
else
	scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP":~/
fi
