#!/usr/bin/env bash
# a script that sets up an nginx server on load balancer server and addes
# a custom header
apt-get update
apt-get install nginx -y

#creating an index file
touch /var/www/html/custom_404.html

echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

#adding content to the index file
echo "Hello world" > /var/www/html/index.html
 


printf %s "server{
	listen		80 default_server;
	listen 		[::]:80 default_server;
	root		/var/www/html;
	index		index.html index.htm;
	add_header	X-Served-By $HOSTNAME;
	
	location /redirect_me {
	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	error_page 404 /custom_404.html;
	location /custom_404 {
	root /var/www/html;
	internal;
	}
}" > /etc/nginx/sites-available/default

serviec nginx restart
