#!/usr/bin/env bash
#Install haproxy and configurate both servers

apt-get -y update
apt-get -y install haproxy
echo -e "\nfrontend front\n\tbind *:80\n\tmode http\n\tdefault_backend back\n\nbackend back\n\tbalance roundrobin\n\tserver 39028-web-01 107.22.144.182:80 check\n\tserver 39028-web-02 18.206.206.84:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
