#!/usr/bin/env bash
#A script pinging the ip passed as an argument
#Author: Kaleab Shiferaw Girma
if [[ $# -ge 1 ]];
then
	ping -c 5 "$1"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
