#!/usr/bin/env bash
# a script that applies a condition
#Author: Kaleab Shiferaw Girma
counter=1
while [ $counter -le 10 ]
do
echo "Best School"
if [ $counter -eq 9 ]
then
echo "Hi"
fi
counter="$((counter + 1))"
done
