#!/usr/bin/env bash
#if, elif and else condition specifiers used in this script
#Author: kaleab shiferaw Girma
i=1
while [ $i -le 10 ]
do
if [ $i -eq 4 ]
then
echo "bad luck"
elif [ $i -eq 8 ]
then
echo "good luck"
else
echo "Best School"
fi
i=$((i + 1))
done
