#!/usr/bin/env bash
#a script checking for a school file existance and more info
#Author: Kaleab Shiferaw Girma
if [ -f "school" ] || [ -d "school" ]
then
echo "school file exists"
if [ -s "school" ]
then
echo "school file is not empty"
else
echo "school file is empty"
fi
if [ -f "school" ]
then
echo "school file is a regular file"
fi
else
echo "school file does not exist"
fi
